In [8]:
from scipy.io import wavfile
import numpy as np
import os
import sys


def load_dataset(dataPathRoot):
    
    dataset = []
    for dirName,subdirList, fileList in os.walk(dataPathRoot):
        for fname in fileList:
            fullFilename = os.path.join(dirName, fname)
                
            if fname.endswith(".wav"):
                try:
                    (fs,data) = wavfile.read(fullFilename)
                    print(data)
                    print(fs)
                except ValueError as e:
                    #print('You should use nist2wav.sh to convert NIST format file to WAV file first')
                    f = Sndfile(fullFilename, 'r')
                    nframes = sf.nframes
                    sig = sf.read_frames(nframes)
                    rate = sf.samplerate
                    print(nframes)
            if fname.endswith('.wv1') or fname.endswith('.wv2'):
                print('Found')
                
    return dataset
                
    
dataset = load_dataset("/home/erika/Documents/Licenta/datasets/timit_small")

print(len(dataset))

[-14 -11   3 ...   5   1   9]
16000
[12 -1  2 ... -1 -3 -3]
16000
[ 9 -2  1 ...  2  0  2]
16000
[21 -6  6 ...  0 -2 -1]
16000
[14 -2  2 ...  1  1  7]
16000
[-3  9  4 ... -3 -9  4]
16000
[-9  1  1 ...  0 -2  1]
16000
[-1 -2 -1 ... -3 -2 -1]
16000
[-14   1  -1 ...   1   4   0]
16000
[-12   5  -2 ...   0  -1   1]
16000
[18 -6  4 ...  3  6  5]
16000
[29 -6  9 ...  2  0  3]
16000
[-31   8  -2 ...  -9   8  11]
16000
[4 3 3 ... 6 2 3]
16000
[ 0 -9  1 ... -1 -1  7]
16000
[-1  4 12 ...  0 -2 -1]
16000
[ 8 10  3 ...  2  3 -6]
16000
[ 4  1 -1 ...  2  3  0]
16000
[ 3  3 -2 ...  1  2  3]
16000
[ 8 -3  2 ...  4  3 -4]
16000
[  1   0   2 ...  -8  -8 -15]
16000
[ 4  4  4 ...  1  1 -2]
16000
[1 2 2 ... 2 0 6]
16000
[ 0  6 -1 ...  5  4  0]
16000
[ 2 -2  2 ...  9  2 24]
16000
[2 2 1 ... 5 7 5]
16000
[4 5 4 ... 4 4 1]
16000
[2 5 1 ... 3 0 5]
16000
[ 5  6  6 ...  0  0 -2]
16000
[2 3 1 ... 4 2 5]
16000
[-20   6  14 ...   4   2  11]
16000
[  0 -19  -4 ...   1  -6   3]
16000
[-1  0  1 ...  6  4 11]
16000
[ 8 

In [2]:
!type python

python is /home/erika/anaconda3/bin/python


In [ ]:
import sys
!conda install --yes --prefix {sys.prefix} libsndfile
